### PR TITLE
Fixed FindAssimp for MacOS

### PR DESCRIPTION
**Pull request by AndySomogyi**
Tested on MacOS, I made sure all the changes were inside a ```if(APPLE)``` blocks

### CODE REVIEW

**Comment by AndySomogyi** [comment]
This second change fixes an issue with creating the Assimp imported target and statically linking to the AssimpImporter plugin on MacOS. I've tested the actual AssimpImporter and so far, seems to be working on MacOS linking to the Assimp from brew.

**Comment by mosra** [comment]
Hi and thanks for the patch!

This might get a bit problematic for you later, as your patch depends on code that's not yet accepted in `master` so it will get rebased quite a lot and thus break your git clone. Not sure what's the best option, but right now to make things as painless for you as possible (because you depend on this to get your work done) I would suggest this for now:

1. this will stay unmerged for a while and you will keep your repository fork as-is, because I guess it works for you now
2. we will continue updating the code and rebasing the repository to get it into a state that's ready for integration into the `magnum-plugins` `master` branch
3. we will integrate your changes along the way (we *have to* in order to get our macOS Travis CI builds green)
4. after everything is integrated, you just switch back to the "upstream" plugins repository

**Comment by AndySomogyi** [comment]
This patch was just for the Squareys/magnum-plugins repo, which I know is not integrated into the main repo yet. That's fine, as the workflow I have now is complicated, but working. 

My current setup is I've created forks of morsa/corrade, morsa/magnum and squareyes/magnum-plugins in my github account. Then my repo references these as git submodules. It's ugly pulling from the upstream repos into my forks, but it seems to be working. 

Currently, I'm trying to focus on getting my simulation environment working and getting another few papers published about it, then I need to go back and really re-think the workflow. 

The FindAssimp.cmake also needs to be reevaluated when I get a chance, as it's not very general, nor robust at the moment. 

At the moment, I'll just continue rebasing off the Squareyes repo for plugins, and keep that as my upstream repo.

**Comment by mosra** [comment]
> Currently, I'm trying to focus on getting my simulation environment working and getting another few papers published about it, then I need to go back and really re-think the workflow.

Sure! :) Focus on what's important for you and we'll try to finish and clean this up in the meantime.

> The FindAssimp.cmake also needs to be reevaluated when I get a chance, as it's not very general, nor robust at the moment.

I have a pretty clear idea how it should look to be robust on all desktop platforms (see the discussion on mosra/magnum-plugins#31), so I guess there's not much more you need to do.

**Comment by mosra** [comment]
The Assimp PR was merged into master and according to the CIs it should work well also on macOS. @AndySomogyi can you verify?

I'd close this then.

**Comment by AndySomogyi** [comment]
I'll rebase and test on OSX, but will have to wait until next week, I'm stuck teaching a class this week.

**Pull request closed without merging**
